<!DOCTYPE html>
  <?php
 
  ?>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/w3.css">
  <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
  <link rel="stylesheet" href="css/index.css">

  <title>Chat</title>
</head>
<body>
  <h1>CHAT</h1>
  <p onclick="a('settingsDiv').style.display = 'block' "><i class="fa fa-setting">Chat Settings</i></p>
  <p onclick="a('notif').style.display = 'block' "><i class="fa fa-setting">Tagged Messages</i></p>
  <div class="w3-center w3-circle w3-red" style="width:60%;margin-left:20%" onclick="changeOffset('back')">Last Messages</div> 
  
  <!--Loads chat here-->
  <div id="conversation" ></div>
  
  <!-- the increaseDiv is usually hidden for better UX experience-->
  <div class="w3-center w3-circle w3-red" style="width:60%;margin-left:20%;display:none" id="increaseOffset" onclick="changeOffset('forward')">Newer Messages</div> 
  <br>
  <br>
  <br>
  <br>
  <br>
  
  <div class="w3-bottom w3-row w3-padding w3-white">
    <!-- This div contains the tag mesaage the user is currently replying -->
    <div id="repliedMessageDiv" style="100%;"></div>

    <!-- Messaging options  -->
    <div class="w3-half">
      <form id="messageForm" enctype="multipart/form-data" autocomplete="false" >
        <!-- Input for  text media-->
        <input style="width:70%;" class="w3-border w3-light-grey" type="text" name="text_chat" id="message">
        
         <!--the id of the new message..it will be generated by a js function in index.js and assigned here...to be sent to the backend-->
        <input type="text" style="display:none"  name="text_chatID" id="MessageID">
        
        <!--input for replied messages...this can be empty if no message is replied-->
        <input type="text" style="display:none"  name="reply_text_chat" id="repliedMessage">
        
          <!-- This allows the backend identify whoever sent the message -->       
        <input type="text" style="display:none"  name="sender" id="sender">
        
        <input type="text" style="display:none"  name="receiver" id="receiver">
       
        <input type="text" style="display:none"  name="channel_type" id="channel_type">
                
        <!-- Input for media chat...just one media file can be sent at once...-->
        <input type="file" style="display:none" id="file" name="file" >
        
        <!--submit button...-->
        <button  class="w3-button" type="submit"><i class="fa fa-send"></i></button>
      </form>
    </div>

    <div class="w3-half" id="messagingOptions">
      <span onclick="document.getElementById('file').click()"><i class="fa fa-upload"></i></span>
      <!--determine() determines if js should start recording a new audio or stop the one currently being recorded and upload the message specially -->
      <!--check out audio.js for everycode requiring  audio-->
    <!--  <span onclick="determine()"><i class="fa fa-microphone"></i></span>-->
    </div>
  </div>
  
  <!--Settings div...invicinble..only shows when settings icon is clicked -->
  <div id="settingsDiv" style="display:none;position:fixed;top:25%;left:25%;background-color:white;width:50%;height:50%">
   <form id="settingsForm" enctype="application/x-www-form-urlencoded">
     <h3>Block user</h3>
     <p>Admin Priviledges only</p>
     <input type="text" style="display:none" class="w3-input" id="blocker" name="blocker" <?php echo "readonly";  ?>>
     <input type="text" class="w3-input" id="channel" name="channel" required>
     <input type="text" class="w3-input" id="blockee"name="blockee" required>
     
     <select id="block_type" name="block_type">
       <option value="block">Block</option>
       <option value="unblock">Unblock</option>
     </select>
     <button type="submit">Confirm</button>
   </form> 
    
  </div>

  <div id="notif" style="display:none;position:fixed;top:0;left:25%;background-color:white;width:75%;height:100%">
   hxhxjzjxjz
  </div>
  <!--Load JS scripts-->
  <script src="channel_js/jquery-1.9.1.js"></script>
  <script src="channel_js/global.js"></script> 
  <script src="channel_js/validation.js"></script> 
  <script src="channel_js/sendmessage.js"></script> 
  <script src="channel_js/automaticallyLoadRecipientMessage.js"></script>
  <script src="channel_js/settings.js"></script> 
  <script src="channel_js/saveToChatHistory.js"></script> 

</body>
</html>

